version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./migrations:/var/www/html/migrations
      - ./vendor:/var/www/html/vendor
    working_dir: /var/www/html/public
    depends_on:
      - mysql
    container_name: clear-php-container
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: clear-nginx-container
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS: "1"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    container_name: clear-mysql-container
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge